version: "3"

services:

    v2fly:
        build:
            context: ./v2ray
            args:
                - vlessuuid=$vlessuuid
                - vmessuuid=$vmessuuid
                - vlesspath=$vlesspath
                - vmesspath=$vmesspath
        volumes: 
            - ./log:/var/log/v2ray
        networks:
            - v2net
        restart: always

    v2caddy:
        image: caddy
        volumes:
            - ./caddy:/etc/caddy
            - ./html:/var/www/html
        ports: 
            - 443:443
            - 80:80
        networks:
            - v2net
        restart: always


    v2py:
        build:
            context: ./v2py
            args:
                - yourownbearer=$yourownbearer
                - yourownzoneid=$yourownzoneid
                - vlesspath=$vlesspath
                - vmesspath=$vmesspath
        depends_on:
            - v2caddy
        networks:
            - v2net
        env_file:
            - .env

networks:
    v2net:
        driver: bridge